version: '3.8'

services:
  maas:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=your_db_user # Replace with your database user
      - DATABASE_PASSWORD=your_db_password # Replace with your database password
      - DATABASE_NAME=maasdb
    volumes:
      - ./config.yaml:/app/config.yaml

  postgres:
    image: postgres:14
    environment:
      - POSTGRES_USER=your_db_user # Replace with your database user
      - POSTGRES_PASSWORD=your_db_password # Replace with your database password
      - POSTGRES_DB=maasdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: